services:
  dockerlock:
    build:
      context: .
      dockerfile: Dockerfile
    image: dockerlock
    container_name: dockerlock
    ports:
      - "8886:8888"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
