name: health_analysis_env
channels:
- conda-forge
dependencies:
- python=3.12.12
- pandas=2.3.3
- scikit-learn=1.7.2
- altair=6.0.0
- jupyterlab=4.5.0
- seaborn=0.13.2
- pandera=0.27.0
- conda-lock=3.0.4
- matplotlib=3.10.8
- numpy[version='<2.0']
