name: health_analysis_env
channels:
- conda-forge
dependencies:
- python=3.12.12
- pandas=2.3.3
- altair=6.0.0
- jupyterlab=4.5.0
- seaborn=0.13.2
- pandera=0.27.0
- conda-lock=3.0.4
- matplotlib=3.10.8
- click=8.3.1
- quarto=1.8.26
- tabulate=0.9.0
- requests=2.32.5
- numpy=1.26.4
- pytest=9.0.2
- make=4.4.1
- scikit-learn=1.7.2